theme: jekyll-theme-minimal
title: Tutorial for Aboretum-based DE geneset analysis
description: A tutorial which includes Arboretum & findTransitionGenesets with an example dataset.
logo: 
show_downloads: true
