if [ $# -ne 3 ]
then
	echo "Usage: batchGen inputdir ouputdir suffix"
	exit
fi

INPUTDIR=$1
OUTPUTDIR=$2
#SAMPLESPERGENE=$3
DATASETID=0
FGCONVTOOL=./genData
#while [ $DATASETID -lt 100 ]
while [ $DATASETID -lt 50 ]
do
	EXPRFILE=$INPUTDIR/dataset${DATASETID}.txt
	#grep -v "Genes" $EXPRFILE > temp.txt
	#cp temp.txt $EXPRFILE
	#MODELSUFF=$OUTPUTDIR/fgin${DATASETID}
	MODELSUFF=$OUTPUTDIR/${3}${DATASETID}
	LOGTRANS=1
	SAMPLESPERGENE=`awk '{print NF-1}' $EXPRFILE | sort -u`
	#echo "$FGCONVTOOL $EXPRFILE $LOGTRANS $MODELSUFF $SAMPLESPERGENE fgraph 0 none"
	echo "$FGCONVTOOL $EXPRFILE $LOGTRANS $MODELSUFF $SAMPLESPERGENE fgraph 0 none"
	$FGCONVTOOL $EXPRFILE $LOGTRANS $MODELSUFF $SAMPLESPERGENE fgraph 0 none
	#$FGCONVTOOL $EXPRFILE $LOGTRANS $MODELSUFF $SAMPLESPERGENE fgraph 0 zeromean
	DATASETID=`expr $DATASETID + 1`
done
